#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
git config --global user.name "dilaralong"
git config --global user.email dlongg@vt.edu
git config --global credential.helper 'cache --timeout=600000000'
